name: Deploy my protfolio application on dev server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: npm i -g npm@8.5.0
      - run: node -v
      - run: npm -v
      - run: npm install
      - run: npm run build

      - name: Build status
        if: ${{ failure() }}
        run: "Failed"

      # - name: Notify slack success
      #   id: slack
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      #   uses: voxmedia/github-action-slack-notify-build@v1
      #   with:
      #     channel: deployment-notification
      #     status: SUCCESS
      #     color: warning

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  deploy:
    needs: build
    name: Dev deployment process
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "This step will always run"
