name: Deploy my protfolio application on dev server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.14.2
        id: nodestep
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: npm i -g npm@8.5.0
      - run: node -v
      - run: npm -v
      - run: npm install
      - run: npm run build

      - name: Build status
        if: ${{ failure() }}
        run: "Failed"

      - name: Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://filamentphp.com/images/icon.png
          SLACK_MESSAGE: "Build failed on test build"
          SLACK_TITLE: Application build test
          SLACK_USERNAME: Customer Panel(dev server)
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Dev deployment process
        if: ${{ steps.nodestep.outcome.success }}
        run: echo "Success step 2 is running"
