name: Deploy my protfolio application on dev server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: npm i -g npm@8.5.0
      - run: node -v
      - run: npm -v
      - run: npm install
      - run: npm run build

      - name: Build status
        if: ${{ failure() }}
        run: "Failed"

      - name: Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://filamentphp.com/images/icon.png
          SLACK_MESSAGE: "Build failed on test build"
          SLACK_TITLE: Application build test
          SLACK_USERNAME: Customer Panel(dev server)
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  # slackNotification:
  #   name: Slack Notification
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Slack Notification
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  deploy:
    needs: build
    name: Dev deployment process
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "This step will always run"
